workflows:
  ios-release:
    name: iOS Release

    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

      ios_signing:
        provisioning_profiles:
          - sosmama_profile

    scripts:
      - flutter pub get
      - cd ios && pod install
      - flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa